name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install
        run: npm install

      - name: create env
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: .env
          FILE_DATA: ${{secrets.DATABASE_URL}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kmpaiva/desafio-backend-pitang:latest
