name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install
        run: npm install

      - name: create env
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: |
          touch .env
          echo DATABASE_URL="$DATABASE_URL"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kmpaiva/desafio-backend-pitang:latest
          secrets: |
            "DATABASE_URL=${{secrets.DATABASE_URL}}"
