name: test

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install
        run: yarn install

      - name: create env
        run: |
          touch .env
          echo DATABASE_URL=hue >> .env

      - name: run tests
        run: yarn test
