name: test

on:
  - pull_request

env:
  DATABASE_URL: postgresql://hue

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install
        run: yarn install

      - name: run tests
        run: yarn test
